### ISSUE TITLE
During training, the loss_cls_neg does not reduce, but the results appear good

### ISSUE THREAD

**Issue by StarBurstStream0** [strongwolf/DW#1]
Hi, i train dw in my dataset, but find the loss_cls_neg does not reduce, but increases. However, the test results seem good. 
Is it normal for this situation?
How does this loss work?
I would like to try if removing this loss and check the results again.

**Comment by strongwolf** [comment]
Hi. The situation is normal. One possible reason is that the neg avg factor is dynamically calculated.  Removing this loss will obviously decrease the performance according to my experiments on COCO.

**Comment by StarBurstStream0** [comment]
> Hi. The situation is normal. One possible reason is that the neg avg factor is dynamically calculated. Removing this loss will obviously decrease the performance according to my experiments on COCO.

Thanks a lot.
