### ISSUE TITLE
Why not limit the regression range for each location of each FPN level?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [strongwolf/DW#17]
In FCOS, each FPN level is responsible for predicting objects of different sizes. But in DW, each object is predicted by all FPN levels, why?
![image](https://user-images.githubusercontent.com/26771037/179434087-df006215-23c4-4bae-88fe-5660696d8a3f.png)

**Comment by strongwolf** [comment]
We don't manually restrict each level feature to detect objects within a certain range of sizes.  The selection of which FPN level each GT should be assigned to is decided by our matching matric. Similar ideas can also be found in FreeAnchor and Autoassign.
