### ISSUE TITLE
label assignment in overlap situation

### ISSUE THREAD

**Issue by jacksonsc007** [strongwolf/DW#18]
Hi,  I am really enlightened by your excellent work. Here is my question:
**How to deal with the situation when an anchor appears in anchor bag of multiple gt boxes?**
I have not checked the code yet and I will check it as soon as possible but I am looking forward to your insights.
Thanks a lot.

**Comment by strongwolf** [comment]
In our code, the anchor within the overlapped region will classify and regress multiple gt boxes at the same time with different loss weights. We just find this works well so we don't handle this situation in a special way.

**Comment by jacksonsc007** [comment]
thanks for your prompt reply.
