### ISSUE TITLE
The multi-scale setting

### ISSUE THREAD

**Issue by jshilong** [strongwolf/DW#20]
Thanks for your wonderful work.
I have a question.
Are all multi-scale results of DW in the paper with 1333x[480:960]  setting?

**Comment by strongwolf** [comment]
Yes.  We notice this setting is a little different from several papers and we just follow GFocal loss to use [480:960].

**Comment by jshilong** [comment]
> Yes. We notice this setting is a little different from several papers and we just follow GFocal loss to use [480:960].

Thanks for your reply!
