### ISSUE TITLE
请问可以讲解一下bbox refinement么？

### ISSUE THREAD

**Issue by flibbertigibbet-Y** [strongwolf/DW#22]
RT（确实没看懂，具体是在做什么，动机是啥

**Comment by YilongLv** [comment]
same question for bbox refinement.e. i.e. why do you perform deformable conv?

**Comment by strongwolf** [comment]
我们的意思是每个点回归出来的四个距离不一定是最好的，所以就在每个点上分别再预测上下左右四个点，然后用左点的l，上点的t，右点的r， 下点的b分别代替原来那个点的输出。
