### ISSUE TITLE
box refine 

### ISSUE THREAD

**Issue by lina926** [strongwolf/DW#24]
![1664331512893](https://user-images.githubusercontent.com/71645228/192672801-6e45b407-60eb-4f3f-a934-9f5b6bd14246.png)
橙色点的坐标是怎么来的，比如左边那个橙点，中心点是（i,j），为什么橙点的坐标是（j+△yl, i-△l+△xl）,而不是（i-△l+△xl，j+△yl）？

**Comment by strongwolf** [comment]
中心点的坐标图上写错了，应该是(j,i)，图的caption写的是对的，我后面在arxiv的版本里改一下，谢谢指正。
