### ISSUE TITLE
where is the code of the Probability of being a Negative Sample when IoU between 0.5 and 0.95?

### ISSUE THREAD

**Issue by ycyinchao** [strongwolf/DW#25]
t = lambda x: 1/(0.5**alpha-1)*x**alpha - 1/(0.5**alpha-1)
It looks like, but it doesn't seem like

**Comment by strongwolf** [comment]
For convenience, we set this function to come across point (0.5,1) and (1,0), not (0.95,0). We find there is no difference between (0.95,0) and (1,0).

**Comment by ycyinchao** [comment]
thanks！
