### ISSUE TITLE
Objectness 

### ISSUE THREAD

**Issue by nqxjzm** [strongwolf/DW#29]
Sorry to bother you, I can't understand the meaning the variant "objectness", could you explan it? I would appreciate it very much if you can answer it !

**Comment by strongwolf** [comment]
Many current detectors (especially one-stage detectors) have such a branch predicting a score map of H * W * 1. According to the supervision signals applied to this branch, different methods call this branch differently. It can be called as centerness score (supervised by the distance between the anchor point to the object center point) in FCOS, IoU score in PAA (supervised by the IoU between the predicted box and the GT object) or objectness score in most LA methods (supervised by the category label).

**Comment by nqxjzm** [comment]
OK, I get it
