### ISSUE TITLE
Why to choose different exponentials during the calculation of pos weight ?

### ISSUE THREAD

**Issue by soHardToHaveAName** [strongwolf/DW#3]
https://github.com/strongwolf/DW/blob/27f50e5bf8d9ea021d5fe1a7a7e47e06bc5db208/dw_head.py#L178

Why are the exponentials  in this formula  5 and 3 respectively ?

Thought it would be the same

Is there any explanation?

**Comment by strongwolf** [comment]
This aims to keep a balance between the pos_loss and neg_loss, which we find is very important to the final performance.  Using 5 in the pos_weight and 3 in the pos_avg_factor has the effect of increasing the pos_loss compared with using the same exponentials.

**Comment by soHardToHaveAName** [comment]
> This aims to keep a balance between the pos_loss and neg_loss, which we find is very important to the final performance. Using 5 in the pos_weight and 3 in the pos_avg_factor has the effect of increasing the pos_loss compared with using the same exponentials.

Thanks for your reply !
