### ISSUE TITLE
About bbox refinement

### ISSUE THREAD

**Issue by satuoqaq** [strongwolf/DW#32]
`bbox_pred = self.deform_sampling(decoded_bbox_preds.contiguous(), reg_offset.contiguous()) `

` bbox_pred = F.relu(bbox2distance(points, bbox_pred.permute(0, 2, 3, 1).reshape(-1, 4)).reshape(b, h, w, 4).permute(0, 3, 1, 2).contiguous())`

first line you sample in coarse bbox pred , i think  this is final pred, why you decode again in second line?

**Comment by Icecream-blue-sky** [comment]
```python
bbox_pred = self.deform_sampling(decoded_bbox_preds.contiguous(), reg_offset.contiguous())
```
will return the absolute coordinate of bounding boxes. The second line transforms it to the [l,t,b,r] style.

**Comment by satuoqaq** [comment]
> ```python
> bbox_pred = self.deform_sampling(decoded_bbox_preds.contiguous(), reg_offset.contiguous())
> ```
> 
> will return the absolute coordinate of bounding boxes. The second line transforms it to the [l,t,b,r] style.

my fault, I thought it was distance to bbox again, i got it~
