### ISSUE TITLE
The difference beteen Autoassign and this DW

### ISSUE THREAD

**Issue by CPFelix** [strongwolf/DW#33]
Thank you for your great work! When I read your paper and code, found that its idea and some implementations have some similiar with [Autoassign](https://github.com/Megvii-BaseDetection/AutoAssign),but in paper didn't compare them thoroughly.Can you explain for me the difference beteen them,thanks! @strongwolf

**Comment by CPFelix** [comment]
你好，我简单总结了两者的相同和不同之处，烦请看下是否存在错漏之处！
DW的很多思想和实现与Autoassign相似，具体的：
相同：
1、都针对GT框内候选正样本进行正负权重计算，区分前背景；
2、针对GT框外负样本的负权重均为1；
3、针对GT框内候选正样本的正权重计算都采用分类得分、回归损失、基于高斯分布的中心先验；
区别：
1、Autoassign引入ImpObj分支输出前背景得分（0.9AP），DW保留centerness分支，并增加Box Refine模块获得更加精准的坐标回归（0.7AP）；
2、针对GT框内候选正样本的负权重计算，Autoassign采用关于IOU的单调函数，DW采用基于IOU的分段函数和分类得分；
3、交叉熵的计算，Autoassign将权重和置信度相乘后求交叉熵，DW则将权重放在置信度的交叉熵外；
4、Autoassign没有单独设置回归损失，DW则在正负权重损失之外保留了GIOU回归损失；
5、正置信度的计算，Autoassign采用分类得分、前后景得分、回归损失的耦合，DW则只采用分类得分和centerness得分；

**Comment by strongwolf** [comment]
我们和autoassign的最大的不同是你说的第三点，权重放在了不同的地方。此外，autoassign的权重是可学习的，如果detach掉会影响性能，DW的权重是不学习的完全人为设计的参数。

**Comment by strongwolf** [comment]
我们和autoassign的最大的不同是你说的第三点，权重放在了不同的地方。此外，autoassign的权重是可学习的，如果detach掉会影响性能，DW的权重是不学习的完全人为设计的参数。

**Comment by seacloud-0420** [comment]
@CPFelix  Hi, do you know how DW is used in two-stage detectors? Such as fast-rcnn, is DW applied to the rcnn stage of fast-rcnn？
