### ISSUE TITLE
Training in Custom Dataset

### ISSUE THREAD

**Issue by BlueBlueFF** [strongwolf/DW#4]
When I training in my custom dataset,  - mmdet - INFO - Epoch [24][1350/1388]	lr: 1.000e-04, eta: 0:00:57, time: 1.529, data_time: 0.023, memory: 7116, loss_cls_pos: 0.0950, loss_loc: 0.2806, loss_cls_neg: 0.1053, loss: 0.4809
 the loss_cls_pos seems small than loss_cls_neg, how to only enlarge loss_cls_pos?

**Comment by strongwolf** [comment]
Is the loss_cls_pos smaller than the loss_cls_neg at the beginning of training or only at the late epochs?  I am not sure whether this phenomenon is normal and I think you can have a judgment by checking the mAP.
