### ISSUE TITLE
' DWHead is not in the models registry'"

### ISSUE THREAD

**Issue by GF1447571253** [strongwolf/DW#5]
KeyError: 'DWHead is not in the models registry', How to fix this error? shoud I copy dw_head.py to mmdet/models/dense_heads/ and add from .dw_head import DWHead into __init__.py? I have tried, and it works

**Comment by strongwolf** [comment]
Actually, you can directly run the code outside the mmdet folders.  Clone the **whole** DW code into a place which can be any folder on your machine.  And then run bash dist_train.sh configs/dw_r50_fpn_1x_coco.py 8 --work-dir weights/r50_1x.

**Comment by GF1447571253** [comment]
I did as you said and same error occurs.

**Comment by GF1447571253** [comment]
replied by@[chhluo](https://github.com/chhluo):
you should import these custom modules. Please add the following code in config file you run, refer to https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#.

custom_imports=dict(
    imports=[
        'path to DWHead'
])
There is an example: https://github.com/ZwwWayne/K-Net/blob/5e50ee58957dce972f51096804ff69171c2f072e/configs/det/_base_/models/knet_s3_r50_fpn.py#L140
