### ISSUE TITLE
What does the O(B, 0) in this equation mean?

### ISSUE THREAD

**Issue by JinYuannn** [strongwolf/DW#7]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/88826210/165056044-bab2206b-5920-447d-918a-b9b31a704612.png">
What does the O(B, 0) [or O(B, 1) ...] in the above equation mean? 
And it may be is different with the previously mentioned O(i,j), symbol reuse is not to explain.

**Comment by strongwolf** [comment]
More preciously, O(B,0) should be written as O(B)[0] where O(B) (a vector) means the four predicted offsets (l,t,r,b) at anchor position B and O(B)[0] means the first element of the four predicted offsets.

**Comment by JinYuannn** [comment]
> More preciously, O(B,0) should be written as O(B)[0] where O(B) (a vector) means the four predicted offsets (l,t,r,b) at anchor position B and O(B)[0] means the first element of the four predicted offsets.

Got it, thank you for your reply and thank you for your work.

**Comment by lina926** [comment]
> <img alt="image" width="353" src="https://user-images.githubusercontent.com/88826210/165056044-bab2206b-5920-447d-918a-b9b31a704612.png">
> 
> What does the O(B, 0) [or O(B, 1) ...] in the above equation mean? And it may be is different with the previously mentioned O(i,j), symbol reuse is not to explain.
橙色点的坐标是怎么来的，比如左边那个橙点，中心点是（i,j），为什么橙点的坐标是（j+△yl, i-△l+△xl）,而不是（i-△l+△xl，j+△yl）？
![1664335601232](https://user-images.githubusercontent.com/71645228/192680700-401954c7-473f-4cb5-a196-ff2b4bef44a2.png)
