### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by DDGRCF** [strongwolf/DW#9]
When I train the DW in coco, I have an unexpected problem, as following:
`CUDA error: device-side assert triggered` and it happen when I train some epochs.
I think It happen in         
`loc_loss = F.binary_cross_entropy` and `cls_loss = F.binary_cross_entropy`, but I can't figure out why it happens.
Can you get me some helps?

**Comment by strongwolf** [comment]
How many GPUs do you use?

**Comment by DDGRCF** [comment]
> How many GPUs do you use?
![2022-05-04_14-35](https://user-images.githubusercontent.com/63622528/166632886-62bde084-0ccf-40da-b5f7-a98ef3774e3e.png)

1 GPU. This problem seems to only occur in very rare cases.

**Comment by strongwolf** [comment]
This phenomenon often occurs in many FCOS-style label assignment methods (not only for DW) when using just 1 GPU. I suggest you can use at least 4 GPUs.

**Comment by DDGRCF** [comment]
> 

OK. Thanks.
